[SDK 491] Parameters tampering protection issue fixed
Countly/countly-sdk-unity pull request #129
Opened 2021-10-07 06:57 UTC by ZahidZafar

2021-11-11 14:34 UTC, ArtursKadikis requested changes
In the tests don't transform "NameValueCollection" into "Dictionary<string, string>". The "NameValueCollection" objects should be used directly. There is no reason to perform that transformation.


Where possible, remove tabs from the function header "summary"

2021-11-11 14:34 UTC, ArtursKadikis commented on Assets/Plugins/CountlySDK/Helpers/RequestCountlyHelper.cs
> +            if (_config.EnablePost || model.RequestData.Length > 1800) {
Change the value to 2000 to be inline with the SDK spec

2021-11-11 14:34 UTC, ArtursKadikis commented on Assets/Plugins/CountlySDK/Helpers/RequestBuilder.cs
> +    ///     Builds request by adding Base params into supplied queryParams parameters.
Remove "tabs" from this description

2021-11-11 14:34 UTC, ArtursKadikis commented on Assets/Plugins/CountlySDK/Helpers/RequestBuilder.cs
> +    ///     Builds query string using supplied queryParams parameters.
Remove "tabs" from this description

2021-11-11 15:06 UTC, ArtursKadikis requested changes
Does not fix all requested changes

2021-11-15 18:41 UTC, ArtursKadikis requested changes
Commented out code lines should be removed. They should not be left in to pollute the SDK.

Add at least 1 migration test where it starts with "currentVersion" being "0" and that migration goes through both steps.

2021-11-16 08:24 UTC, ZahidZafar commented
> Commented out code lines should be removed. They should not be left in to pollute the SDK.
> 
> Add at least 1 migration test where it starts with "currentVersion" being "0" and that migration goes through both steps.

SDK run migration during init. If set currentVersion = 0 and run migration then there will be exception while migrating from 0 to 1.
 We can not manually migrate from schema 0 to 1.

2021-11-16 09:18 UTC, ArtursKadikis commented
Tests need to be reworked so that the migration is happening during the SDK "init" call.

2021-11-18 23:42 UTC, ArtursKadikis requested changes

2021-11-18 23:42 UTC, ArtursKadikis commented on Assets/Tests/PlayModeTests/MigrationTests.cs
> +            CountlyConfiguration configuration = new CountlyConfiguration {
The initial schema version in this test should be 1. Currently it would already be 2 and no migration on empty DB would be run.

2021-11-18 23:42 UTC, ArtursKadikis commented on Assets/Tests/PlayModeTests/MigrationTests.cs
> +            Assert.AreEqual(2, Countly.Instance.StorageHelper.SchemaVersion);
This check is not future proof and will break in the future when another migration is added.

2021-11-19 12:22 UTC, merged