Metric Helper Class
Countly/countly-sdk-unity pull request #182
Opened 2023-10-31 11:47 UTC by AliRKat

2023-10-31 11:59 UTC, ArtursKadikis requested changes
Bad naming "metric helper" for metric override. 
Config should get a setter
no additions to Countly config model
no usage of "Countly.instance" within the SDK.
try adding metric helper as protected field in config, otherwise pass it to all modules

"CountlyMetricModel' should set all fields during its constructor

no comments for tests

Rework test. For now create them without initializing the SDK

2023-10-31 11:59 UTC, ArtursKadikis commented on Assets/Tests/PlayModeTests/HelpersTests.cs
> +            Countly.Instance.ClearStorage();
put this in test utility call. "TestCleanup"
call it before the test

2023-10-31 11:59 UTC, ArtursKadikis commented on Assets/Tests/PlayModeTests/HelpersTests.cs
> +            Countly.Instance.ClearStorage();
and after

2023-11-02 12:46 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] Add metricHelper class](https://trello.com/c/cUDbRijZ/970-unity-add-metrichelper-class)

2023-11-03 12:07 UTC, ArtursKadikis requested changes
Eliminate metric model. Introduce custom metrics

2023-11-08 14:06 UTC, merged