Requested Test Added
Countly/countly-sdk-unity pull request #183
Opened 2023-11-10 14:09 UTC by AliRKat

Session metric override test added.

Changelog entry for metric override added.

overridenMetrics field in MetricHelper changed into internal, which was causing a compiler error while it was private.

2023-11-10 14:09 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] Add overriden metric test for the session request.](https://trello.com/c/63SJn0wC/1089-unity-add-overriden-metric-test-for-the-session-request)

2023-11-13 12:17 UTC, ArtursKadikis requested changes
use the setter for the tests

2023-11-13 12:17 UTC, ArtursKadikis commented on CHANGELOG.md
> +* Added MetricHelper class and "overriddenMetrics" field in the configuration object, allowing to pass custom or overridden metrics.
reword this and don't mention metric helper

2023-11-13 12:17 UTC, ArtursKadikis commented on Assets/Plugins/CountlySDK/Models/CountlyConfiguration.cs
> -        public void SetMetricOverride(Dictionary<string, string> overridenMetrics)
add this back in

2023-11-14 13:01 UTC, merged