Added SetId functionality
Countly/countly-sdk-unity pull request #204
Opened 2024-03-21 15:00 UTC by AliRKat

2024-03-21 15:01 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] implement "setID"](https://trello.com/c/r9lENtX9/1611-unity-implement-setid)

2024-03-22 08:39 UTC, turtledreams requested changes

2024-03-22 08:39 UTC, turtledreams commented on Assets/Tests/PlayModeTests/DeviceIdTests.cs
> +                ValidateDeviceIDAndType(Countly.Instance, id, expectedIdType, true);
I would like early return and removing else, for better readability or you can change the device id you feed to validate function with if check and have one validatedeviceIDandtype only. You think the same?

2024-03-22 08:39 UTC, turtledreams commented on Assets/Tests/PlayModeTests/DeviceIdTests.cs
> +                CountlyConfiguration config = new CountlyConfiguration(_appKey, _serverUrl);
here again set the config and device id type alone to reduce repetition

2024-03-22 08:39 UTC, turtledreams commented on Assets/Tests/PlayModeTests/DeviceIdTests.cs
> +
can you add 1 more test where you double call setid with different values and verify at each step id is correct

2024-03-22 11:55 UTC, ArtursKadikis requested changes
styling needs to be fixed

2024-03-25 06:17 UTC, ijunaid approved these changes
Overall looks good to me, some if else conditions can improve to remove the repeated code as D mentioned.

2024-03-25 06:17 UTC, ijunaid commented on Assets/Tests/PlayModeTests/DeviceIdTests.cs
> +            Countly.Instance.Init(config);
Why aren't we just using TestUtility.CreateBaseConfig() instead of making a whole new config?

2024-03-25 07:34 UTC, turtledreams requested changes

2024-03-25 07:34 UTC, turtledreams commented on Assets/Countly/Plugins/CountlySDK/Services/DeviceIdCountlyService.cs
> +        private async void SetIdInternal(string newDeviceId)
seems like this should be Task instead of void <3

2024-03-26 06:29 UTC, turtledreams requested changes
Yeap good improvements. I think we are almost there. Only thing remains is to check if we are merging or not merging.
so we check type and id before and after setID. But we do not check if that change happened with merge or without merge (or it seems). might use same validators that exist for change id methods if they exist

2024-03-26 06:29 UTC, turtledreams commented on Assets/Tests/PlayModeTests/DeviceIdTests.cs
> +            if (startType == DeviceIdType.SDKGenerated) {
this code is perfectly fine. a suggestion though: you can assign a CountlyConfiguration to a configuration from the if block or the else block initially. then with a single if check you can re-assign it if necessary. this way you would eliminate the else block. only if that would be sth you also like

2024-03-28 11:09 UTC, turtledreams requested changes
merge conflict

2024-03-28 11:18 UTC, AliRKat commented
merge conflict is solved

2024-04-03 05:17 UTC, turtledreams approved these changes

2024-04-08 10:34 UTC, ijunaid approved these changes

2024-04-15 10:35 UTC, merged