Extracted EventTests from EventService PR
Countly/countly-sdk-unity pull request #208
Opened 2024-03-28 11:27 UTC by AliRKat

Extracted EventTests from EventService PR

Reduced the total length by using the new configuration, which also helps to not print warnings to the console.

Functionality is same and all tests are successful

2024-03-28 11:28 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] Extracting EventTests from EventService PR](https://trello.com/c/eejmWMIu/1669-unity-extracting-eventtests-from-eventservice-pr)

2024-04-03 05:27 UTC, turtledreams requested changes
can you check if the IDE is overriding the indentation or the line endings

2024-04-03 09:30 UTC, AliRKat commented
> can you check if the IDE is overriding the indentation or the line endings

I believe it was related to the IDE, because when I switched back to Visual Studio, it got fixed. I'm trying to understand what VSCode overrides. Line endings are same, indentation also looks same. Will dig on it. Other than that refactoring is done without overrides

2024-04-15 05:48 UTC, turtledreams approved these changes

2024-04-15 10:28 UTC, merged