PutAll in CountlyUtils and Tests Added
Countly/countly-sdk-unity pull request #210
Opened 2024-04-17 10:18 UTC by AliRKat

This PR is created for being able to refactor repeating foreach loops in Views PR, and can be useful while working with segmentations

2024-04-29 03:38 UTC, turtledreams requested changes

2024-04-29 03:38 UTC, turtledreams commented on Assets/Countly/Plugins/CountlySDK/CountlyUtils.cs
> +        public void PutAll(Dictionary<string, object> destination, Dictionary<string, object> source, CountlyLogHelper logger)
some things come to my mind are like this:
- maybe a more descriptive name
- Inside the log printing null values seems unnecessary
- count.0 seems like already handled inside the loop
what do you think?

2024-04-29 03:38 UTC, turtledreams commented on Assets/Tests/PlayModeTests/UtilsTests.cs
> +        // 'PutAll' in CountlyUtils
in all tests  it would be better to verify both objects at the end

2024-04-29 03:38 UTC, turtledreams commented on Assets/Countly/Plugins/CountlySDK/CountlyUtils.cs
> +        public void PutAll(Dictionary<string, object> destination, Dictionary<string, object> source, CountlyLogHelper logger)
also you can add a verbose log at the beginning to indicate this method was called

2024-05-08 06:07 UTC, turtledreams approved these changes

2024-05-08 09:54 UTC, arifBurakDemiray approved these changes

2024-05-09 14:19 UTC, merged