Test refactor and extraction
Countly/countly-sdk-unity pull request #212
Opened 2024-04-17 12:10 UTC by AliRKat

Changes on the TestUtility within Views PR are extracted.
With that, I also extracted testing-related changes from the PR (CustomIdProvider and line that breaks in StarRatingTests, which will be refactored later on)
This PR also contains refactoring old views tests with TestUtility (which are exact same with Views PR)

2024-04-17 12:11 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] Old test changes in Views PR are extracted](https://trello.com/c/4U5I9sGm/1731-unity-old-test-changes-in-views-pr-are-extracted)

2024-05-08 10:04 UTC, arifBurakDemiray commented on Assets/Tests/PlayModeTests/TestUtility.cs
> +﻿using Newtonsoft.Json.Linq;
what changed here so much? line endings?

2024-05-08 10:05 UTC, arifBurakDemiray commented on Assets/Tests/PlayModeTests/TestUtility.cs
> +﻿using Newtonsoft.Json.Linq;
new imports added and it changed lines I guess, in case could you check for line endings

2024-05-08 10:06 UTC, arifBurakDemiray commented on Assets/Tests/PlayModeTests/ViewsTests.cs
> -        // We record a view. Consent is required, consent is given. The recorded view is the first view.
what happened to this test

2024-05-08 10:07 UTC, arifBurakDemiray requested changes
Just a catch-up request

2024-05-09 14:25 UTC, merged