Request Repo Check Fixed
Countly/countly-sdk-unity pull request #213
Opened 2024-04-19 11:37 UTC by AliRKat

2024-04-19 11:38 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] RequestCountlyHelper request repo count check needs to be updated](https://trello.com/c/UDs3DFkX/1700-unity-requestcountlyhelper-request-repo-count-check-needs-to-be-updated)

2024-04-29 03:48 UTC, turtledreams requested changes

2024-04-29 03:48 UTC, turtledreams commented on Assets/Countly/Plugins/CountlySDK/Helpers/RequestCountlyHelper.cs
> +            if (_requestRepo.Count >= _config.GetMaxRequestQueueSize()) {
the changes we talked about

2024-05-06 06:42 UTC, arifBurakDemiray commented on Assets/Countly/Plugins/CountlySDK/Helpers/RequestCountlyHelper.cs
>                  Log.Warning("[RequestCountlyHelper] Request Queue is full. Dropping the oldest request.");
maybe logging message could be updated that we are deleting that amount

2024-05-06 06:43 UTC, arifBurakDemiray approved these changes

2024-05-09 14:23 UTC, turtledreams approved these changes

2024-05-09 14:23 UTC, merged