View test check
Countly/countly-sdk-unity pull request #222
Opened 2024-06-10 12:31 UTC by AliRKat

created the branch from the legacy code's bug fix branch, this branch only contains changes in ViewTests.cs

2024-06-10 13:29 UTC, arifBurakDemiray commented on Assets/Countly/Plugins/CountlySDK/Services/ViewCountlyService.cs
> +                StopViewWithNameInternal(name, null);
stop view with name is not:
- clipping view names

2024-06-10 13:31 UTC, arifBurakDemiray requested changes
I have added some comments that might be a missing functionality.
Because currently it seems like they use missing logic. Or they were extra logic and deleted. If the case is extra logic please ping me again, I will approve the PR

2024-06-10 17:32 UTC, AliRKat commented
added the missing logic you mentioned @arifBurakDemiray depending on the review from the others we can keep or remove it. adding obviously seemed as the better option, thanks for giving the heads up

2024-06-10 17:33 UTC, AliRKat commented
also merged the bug fix branch in here, we can gather all under one PR if you wish to @turtledreams

2024-06-11 07:14 UTC, arifBurakDemiray approved these changes
Thanks for your work A-Dono 🙇

2024-06-11 09:23 UTC, peterBrxwn approved these changes

2024-06-12 10:23 UTC, turtledreams requested changes
Oh I see, consent issue found here. So yea fix as mentioned at the other pr and then we can merge em

2024-06-12 13:10 UTC, AliRKat commented
fixed both PRs and merged bug fix in here again, you can merge both or close that one, however you wish @turtledreams

2024-06-24 05:49 UTC, turtledreams approved these changes

2024-06-24 05:49 UTC, merged