array and list support feature and tests
Countly/countly-sdk-unity pull request #226
Opened 2024-06-24 15:01 UTC by AliRKat

first time touching EventTests.cs with VS Code, which caused some changes with formatting in few lines lyk

2024-06-24 15:01 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity] string key and array/list value should be also accepted for segmentations](https://trello.com/c/Ui8UdC3R/1871-unity-string-key-and-array-list-value-should-be-also-accepted-for-segmentations)

2024-06-25 07:40 UTC, arifBurakDemiray requested changes
It is all cool, thanks for your efforts. <3
Please also add unsupported data types cases, like provided list of object or map
And please also test views. Where client can provide segmentation

2024-06-25 09:48 UTC, peterBrxwn approved these changes

2024-06-25 11:17 UTC, arifBurakDemiray commented on Assets/Tests/PlayModeTests/EventTests.cs
> +            Dictionary<string, object> expectedSegm = new Dictionary<string, object>{
maybe couple of invalid types to here

2024-06-25 11:19 UTC, arifBurakDemiray approved these changes

2024-07-03 06:54 UTC, turtledreams requested changes
Please add mixed types to the tests too, like List<object> with whatever u can imagine inside. wanna see what happens. also for naming of methods you introduced pleas go over them one more time. are they succinct, can we more generalize them etc

2024-07-04 06:53 UTC, arifBurakDemiray approved these changes

2024-07-08 09:53 UTC, turtledreams requested changes
I think the thing we talked about last time was to make the log that prints the removed key value pair a little bit better. modify that and lets merge

2024-07-10 14:18 UTC, merged